CREATE TABLE board(
	BOARD_NUM int not null primary key auto_increment,
	BOARD_NAME VARCHAR(20),
	BOARD_PASS VARCHAR(15),
	BOARD_SUBJECT VARCHAR(50),
	BOARD_CONTENT text,
	BOARD_FILE VARCHAR(50),
	BOARD_RE_REF int,
	BOARD_RE_LEV int,
	BOARD_RE_SEQ int,
	BOARD_READCOUNT int,
	BOARD_DATE date
);
